version: "3"

services:
  web:
    build: ./app
    expose:
      - "5000"
    networks:
      - calcnet

  nginx:
    image: nginx:latest
    ports:
      - "4000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    networks:
      - calcnet

networks:
  calcnet:
